<?php

namespace ContainerAPyEbBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SFnbXKSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SFnbXKS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SFnbXKS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificatRepository' => ['privates', 'App\\Repository\\CertificatRepository', 'getCertificatRepositoryService', true],
        ], [
            'certificatRepository' => 'App\\Repository\\CertificatRepository',
        ]);
    }
}
