<?php

namespace ContainerAPyEbBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LL4RhHkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lL4RhHk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lL4RhHk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificat' => ['privates', '.errored..service_locator.lL4RhHk.App\\Entity\\Certificat', NULL, 'Cannot autowire service ".service_locator.lL4RhHk": it needs an instance of "App\\Entity\\Certificat" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'certificat' => 'App\\Entity\\Certificat',
            'entityManager' => '?',
        ]);
    }
}
