<?php

namespace ContainerAPyEbBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I7KA4aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i7KA4a_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i7KA4a_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificatRepository' => ['privates', 'App\\Repository\\CertificatRepository', 'getCertificatRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
        ], [
            'certificatRepository' => 'App\\Repository\\CertificatRepository',
            'entityManager' => '?',
            'quizRepository' => 'App\\Repository\\QuizRepository',
        ]);
    }
}
