<?php

namespace ContainerAPyEbBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCertificat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lL4RhHk.App\Entity\Certificat' shared service.
     *
     * @return \App\Entity\Certificat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lL4RhHk": it needs an instance of "App\\Entity\\Certificat" but this type has been excluded in "config/services.yaml".');
    }
}
