<?php

namespace ContainerAPyEbBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHuggingFaceServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\HuggingFaceService' shared autowired service.
     *
     * @return \App\Service\HuggingFaceService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\HuggingFaceService": argument "$httpClient" of method "__construct()" has type "App\\Service\\HttpClientInterface" but this class was not found.');
    }
}
