security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: /login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/home, roles: [ROLE_TEACHER, ROLE_STUDENT] }
        - { path: ^/base, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN: [ROLE_TEACHER, ROLE_STUDENT, ROLE_USER]
        ROLE_TEACHER: [ROLE_USER]
        ROLE_STUDENT: [ROLE_USER]
    