<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LYGUFchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LYGUFch' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LYGUFch'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feed' => ['privates', '.errored..service_locator.LYGUFch.App\\Entity\\Feed', NULL, 'Cannot autowire service ".service_locator.LYGUFch": it needs an instance of "App\\Entity\\Feed" but this type has been excluded in "config/services.yaml".'],
        ], [
            'feed' => 'App\\Entity\\Feed',
        ]);
    }
}
