<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PQOk1gWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pQOk1gW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pQOk1gW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avaibility' => ['privates', '.errored..service_locator.pQOk1gW.App\\Entity\\Avaibility', NULL, 'Cannot autowire service ".service_locator.pQOk1gW": it needs an instance of "App\\Entity\\Avaibility" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'avaibility' => 'App\\Entity\\Avaibility',
            'doctrine' => '?',
        ]);
    }
}
