<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Elc53hlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Elc53hl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Elc53hl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Avaibility' => ['privates', '.errored..service_locator.Elc53hl.App\\Entity\\Avaibility', NULL, 'Cannot autowire service ".service_locator.Elc53hl": it needs an instance of "App\\Entity\\Avaibility" but this type has been excluded in "config/services.yaml".'],
        ], [
            'Avaibility' => 'App\\Entity\\Avaibility',
        ]);
    }
}
