<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FsWJUcaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fsWJUca' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fsWJUca'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'feedRepository' => ['privates', 'App\\Repository\\FeedRepository', 'getFeedRepositoryService', true],
        ], [
            'feedRepository' => 'App\\Repository\\FeedRepository',
        ]);
    }
}
