<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3VopjwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3_vopjw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3_vopjw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.3_vopjw.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.3_vopjw": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
        ], [
            'event' => 'App\\Entity\\Event',
            'logger' => '?',
        ]);
    }
}
