<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J9KZWIUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J9KZWIU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J9KZWIU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryevent' => ['privates', '.errored..service_locator.J9KZWIU.App\\Entity\\categoryevent', NULL, 'Cannot autowire service ".service_locator.J9KZWIU": it needs an instance of "App\\Entity\\categoryevent" but this type has been excluded in "config/services.yaml".'],
        ], [
            'categoryevent' => 'App\\Entity\\categoryevent',
        ]);
    }
}
