<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OJeM7a0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oJeM7a0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oJeM7a0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'AvaibilityRepository' => ['privates', 'App\\Repository\\AvaibilityRepository', 'getAvaibilityRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'AvaibilityRepository' => 'App\\Repository\\AvaibilityRepository',
            'entityManager' => '?',
        ]);
    }
}
