<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZjNxpNJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zjNxpNJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zjNxpNJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hub' => ['privates', 'mercure.hub.default.traceable', 'getMercure_Hub_Default_TraceableService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', false],
        ], [
            'em' => '?',
            'hub' => '?',
            'security' => '?',
        ]);
    }
}
