<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvaibilityRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\AvaibilityRepository' shared autowired service.
     *
     * @return \App\Repository\AvaibilityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'AvaibilityRepository.php';

        return $container->privates['App\\Repository\\AvaibilityRepository'] = new \App\Repository\AvaibilityRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
