<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryevent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ywVmH_A.App\Entity\categoryevent' shared service.
     *
     * @return \App\Entity\categoryevent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ywVmH_A": it needs an instance of "App\\Entity\\categoryevent" but this type has been excluded in "config/services.yaml".');
    }
}
