<?php

namespace ContainerPMkOmV7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHuggingFaceServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\HuggingFaceService' shared autowired service.
     *
     * @return \App\Service\HuggingFaceService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HuggingFaceService.php';

        return $container->privates['App\\Service\\HuggingFaceService'] = new \App\Service\HuggingFaceService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('HUGGING_FACE_API_TOKEN'));
    }
}
