<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Quiz extends \App\Entity\Quiz implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cours' => [parent::class, 'cours', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null],
        "\0".parent::class."\0".'prixPiece' => [parent::class, 'prixPiece', null],
        "\0".parent::class."\0".'questions' => [parent::class, 'questions', null],
        "\0".parent::class."\0".'reponse_utilisateur' => [parent::class, 'reponse_utilisateur', null],
        'cours' => [parent::class, 'cours', null],
        'id' => [parent::class, 'id', null],
        'note' => [parent::class, 'note', null],
        'prixPiece' => [parent::class, 'prixPiece', null],
        'questions' => [parent::class, 'questions', null],
        'reponse_utilisateur' => [parent::class, 'reponse_utilisateur', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
