<?php

namespace ContainerFwYjhVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WkyPVZVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WkyPVZV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WkyPVZV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'favorite' => ['privates', '.errored..service_locator.WkyPVZV.App\\Entity\\Favorite', NULL, 'Cannot autowire service ".service_locator.WkyPVZV": it needs an instance of "App\\Entity\\Favorite" but this type has been excluded in "config/services.yaml".'],
        ], [
            'favorite' => 'App\\Entity\\Favorite',
        ]);
    }
}
