<?php

namespace ContainerFwYjhVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SQA8h_CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sQA8h.C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sQA8h.C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'whatsappService' => ['privates', 'App\\Service\\WhatsAppService', 'getWhatsAppServiceService', true],
        ], [
            'whatsappService' => 'App\\Service\\WhatsAppService',
        ]);
    }
}
