<?php

namespace ContainerFwYjhVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CPgVA8rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cPgVA8r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cPgVA8r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'abonnement' => ['privates', '.errored..service_locator.cPgVA8r.App\\Entity\\Abonnement', NULL, 'Cannot autowire service ".service_locator.cPgVA8r": it needs an instance of "App\\Entity\\Abonnement" but this type has been excluded in "config/services.yaml".'],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
        ], [
            'abonnement' => 'App\\Entity\\Abonnement',
            'urlGenerator' => '?',
        ]);
    }
}
