<?php

namespace ContainerFwYjhVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryeventRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\categoryeventRepository' shared autowired service.
     *
     * @return \App\Repository\categoryeventRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'categoryeventRepository.php';

        return $container->privates['App\\Repository\\categoryeventRepository'] = new \App\Repository\categoryeventRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
