<?php

namespace ContainerFwYjhVe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWhatsAppServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\WhatsAppService' shared autowired service.
     *
     * @return \App\Service\WhatsAppService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'WhatsAppService.php';

        return $container->privates['App\\Service\\WhatsAppService'] = new \App\Service\WhatsAppService($container->getEnv('TWILIO_ACCOUNT_SID'), $container->getEnv('TWILIO_AUTH_TOKEN'));
    }
}
