<?php

namespace Container7wdYJuB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FeedController' shared autowired service.
     *
     * @return \App\Controller\FeedController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'FeedController.php';

        $container->services['App\\Controller\\FeedController'] = $instance = new \App\Controller\FeedController();

        $instance->setContainer(($container->privates['.service_locator.282XHtU'] ?? $container->load('get_ServiceLocator_282XHtUService'))->withContext('App\\Controller\\FeedController', $container));

        return $instance;
    }
}
