<?php

namespace Container7wdYJuB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeed2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LYGUFch.App\Entity\Feed' shared service.
     *
     * @return \App\Entity\Feed
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LYGUFch": it needs an instance of "App\\Entity\\Feed" but this type has been excluded in "config/services.yaml".');
    }
}
