<?php

namespace Container9xfWSZO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XNIL6fsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XNIL6fs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XNIL6fs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CommentaireController::delete' => ['privates', '.service_locator.ZfwS4tl', 'get_ServiceLocator_ZfwS4tlService', true],
            'App\\Controller\\CommentaireController::deleteBack' => ['privates', '.service_locator.ZfwS4tl', 'get_ServiceLocator_ZfwS4tlService', true],
            'App\\Controller\\CommentaireController::edit' => ['privates', '.service_locator.So5I4VO', 'get_ServiceLocator_So5I4VOService', true],
            'App\\Controller\\CommentaireController::editBack' => ['privates', '.service_locator.So5I4VO', 'get_ServiceLocator_So5I4VOService', true],
            'App\\Controller\\CommentaireController::new' => ['privates', '.service_locator.6OXKtQO', 'get_ServiceLocator_6OXKtQOService', true],
            'App\\Controller\\CommentaireController::newBack' => ['privates', '.service_locator.SoIa2O7', 'get_ServiceLocator_SoIa2O7Service', true],
            'App\\Controller\\CommentaireController::show' => ['privates', '.service_locator.ZfwS4tl', 'get_ServiceLocator_ZfwS4tlService', true],
            'App\\Controller\\CommentaireController::showBack' => ['privates', '.service_locator.ZfwS4tl', 'get_ServiceLocator_ZfwS4tlService', true],
            'App\\Controller\\FeedController::delete' => ['privates', '.service_locator.3yvLtfp', 'get_ServiceLocator_3yvLtfpService', true],
            'App\\Controller\\FeedController::deleteBack' => ['privates', '.service_locator.3yvLtfp', 'get_ServiceLocator_3yvLtfpService', true],
            'App\\Controller\\FeedController::edit' => ['privates', '.service_locator.3yvLtfp', 'get_ServiceLocator_3yvLtfpService', true],
            'App\\Controller\\FeedController::editBack' => ['privates', '.service_locator.3yvLtfp', 'get_ServiceLocator_3yvLtfpService', true],
            'App\\Controller\\FeedController::index' => ['privates', '.service_locator.fsWJUca', 'get_ServiceLocator_FsWJUcaService', true],
            'App\\Controller\\FeedController::indexBack' => ['privates', '.service_locator.fsWJUca', 'get_ServiceLocator_FsWJUcaService', true],
            'App\\Controller\\FeedController::new' => ['privates', '.service_locator.6OXKtQO', 'get_ServiceLocator_6OXKtQOService', true],
            'App\\Controller\\FeedController::newBack' => ['privates', '.service_locator.6OXKtQO', 'get_ServiceLocator_6OXKtQOService', true],
            'App\\Controller\\FeedController::show' => ['privates', '.service_locator.LYGUFch', 'get_ServiceLocator_LYGUFchService', true],
            'App\\Controller\\FeedController::showBack' => ['privates', '.service_locator.LYGUFch', 'get_ServiceLocator_LYGUFchService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CommentaireController:delete' => ['privates', '.service_locator.ZfwS4tl', 'get_ServiceLocator_ZfwS4tlService', true],
            'App\\Controller\\CommentaireController:deleteBack' => ['privates', '.service_locator.ZfwS4tl', 'get_ServiceLocator_ZfwS4tlService', true],
            'App\\Controller\\CommentaireController:edit' => ['privates', '.service_locator.So5I4VO', 'get_ServiceLocator_So5I4VOService', true],
            'App\\Controller\\CommentaireController:editBack' => ['privates', '.service_locator.So5I4VO', 'get_ServiceLocator_So5I4VOService', true],
            'App\\Controller\\CommentaireController:new' => ['privates', '.service_locator.6OXKtQO', 'get_ServiceLocator_6OXKtQOService', true],
            'App\\Controller\\CommentaireController:newBack' => ['privates', '.service_locator.SoIa2O7', 'get_ServiceLocator_SoIa2O7Service', true],
            'App\\Controller\\CommentaireController:show' => ['privates', '.service_locator.ZfwS4tl', 'get_ServiceLocator_ZfwS4tlService', true],
            'App\\Controller\\CommentaireController:showBack' => ['privates', '.service_locator.ZfwS4tl', 'get_ServiceLocator_ZfwS4tlService', true],
            'App\\Controller\\FeedController:delete' => ['privates', '.service_locator.3yvLtfp', 'get_ServiceLocator_3yvLtfpService', true],
            'App\\Controller\\FeedController:deleteBack' => ['privates', '.service_locator.3yvLtfp', 'get_ServiceLocator_3yvLtfpService', true],
            'App\\Controller\\FeedController:edit' => ['privates', '.service_locator.3yvLtfp', 'get_ServiceLocator_3yvLtfpService', true],
            'App\\Controller\\FeedController:editBack' => ['privates', '.service_locator.3yvLtfp', 'get_ServiceLocator_3yvLtfpService', true],
            'App\\Controller\\FeedController:index' => ['privates', '.service_locator.fsWJUca', 'get_ServiceLocator_FsWJUcaService', true],
            'App\\Controller\\FeedController:indexBack' => ['privates', '.service_locator.fsWJUca', 'get_ServiceLocator_FsWJUcaService', true],
            'App\\Controller\\FeedController:new' => ['privates', '.service_locator.6OXKtQO', 'get_ServiceLocator_6OXKtQOService', true],
            'App\\Controller\\FeedController:newBack' => ['privates', '.service_locator.6OXKtQO', 'get_ServiceLocator_6OXKtQOService', true],
            'App\\Controller\\FeedController:show' => ['privates', '.service_locator.LYGUFch', 'get_ServiceLocator_LYGUFchService', true],
            'App\\Controller\\FeedController:showBack' => ['privates', '.service_locator.LYGUFch', 'get_ServiceLocator_LYGUFchService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CommentaireController::delete' => '?',
            'App\\Controller\\CommentaireController::deleteBack' => '?',
            'App\\Controller\\CommentaireController::edit' => '?',
            'App\\Controller\\CommentaireController::editBack' => '?',
            'App\\Controller\\CommentaireController::new' => '?',
            'App\\Controller\\CommentaireController::newBack' => '?',
            'App\\Controller\\CommentaireController::show' => '?',
            'App\\Controller\\CommentaireController::showBack' => '?',
            'App\\Controller\\FeedController::delete' => '?',
            'App\\Controller\\FeedController::deleteBack' => '?',
            'App\\Controller\\FeedController::edit' => '?',
            'App\\Controller\\FeedController::editBack' => '?',
            'App\\Controller\\FeedController::index' => '?',
            'App\\Controller\\FeedController::indexBack' => '?',
            'App\\Controller\\FeedController::new' => '?',
            'App\\Controller\\FeedController::newBack' => '?',
            'App\\Controller\\FeedController::show' => '?',
            'App\\Controller\\FeedController::showBack' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CommentaireController:delete' => '?',
            'App\\Controller\\CommentaireController:deleteBack' => '?',
            'App\\Controller\\CommentaireController:edit' => '?',
            'App\\Controller\\CommentaireController:editBack' => '?',
            'App\\Controller\\CommentaireController:new' => '?',
            'App\\Controller\\CommentaireController:newBack' => '?',
            'App\\Controller\\CommentaireController:show' => '?',
            'App\\Controller\\CommentaireController:showBack' => '?',
            'App\\Controller\\FeedController:delete' => '?',
            'App\\Controller\\FeedController:deleteBack' => '?',
            'App\\Controller\\FeedController:edit' => '?',
            'App\\Controller\\FeedController:editBack' => '?',
            'App\\Controller\\FeedController:index' => '?',
            'App\\Controller\\FeedController:indexBack' => '?',
            'App\\Controller\\FeedController:new' => '?',
            'App\\Controller\\FeedController:newBack' => '?',
            'App\\Controller\\FeedController:show' => '?',
            'App\\Controller\\FeedController:showBack' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
