<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAJlZE4Z\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAJlZE4Z/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAJlZE4Z.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAJlZE4Z\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAJlZE4Z\App_KernelDevDebugContainer([
    'container.build_hash' => 'AJlZE4Z',
    'container.build_id' => 'a379a7f1',
    'container.build_time' => 1740354418,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAJlZE4Z');
