<?php

namespace ContainerAJlZE4Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bxj4TpcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bxj4Tpc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bxj4Tpc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'openAIService' => ['privates', '.errored.sLybbaN', NULL, 'Cannot determine controller argument for "App\\Controller\\OpenAITestController::test()": the $openAIService argument is type-hinted with the non-existent class or interface: "App\\Service\\OpenAIService".'],
        ], [
            'openAIService' => '?',
        ]);
    }
}
