<?php

namespace ContainerAJlZE4Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_II5QP0GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iI5QP0G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iI5QP0G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'certificat' => ['privates', '.errored..service_locator.iI5QP0G.App\\Entity\\Certificat', NULL, 'Cannot autowire service ".service_locator.iI5QP0G": it needs an instance of "App\\Entity\\Certificat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'certificat' => 'App\\Entity\\Certificat',
        ]);
    }
}
