<?php

namespace ContainerAJlZE4Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TSSI_AyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TSSI.ay' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TSSI.ay'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'huggingFaceService' => ['privates', 'App\\Service\\HuggingFaceService', 'getHuggingFaceServiceService', true],
        ], [
            'huggingFaceService' => 'App\\Service\\HuggingFaceService',
        ]);
    }
}
